//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMV2
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRMV2.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Successfully!.
        /// </summary>
        internal static string AddSuccessfully
        {
            get
            {
                return ResourceManager.GetString("AddSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to add new address?.
        /// </summary>
        internal static string AskToAddNewAddress
        {
            get
            {
                return ResourceManager.GetString("AskToAddNewAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this address?.
        /// </summary>
        internal static string AskToDeleteAddress
        {
            get
            {
                return ResourceManager.GetString("AskToDeleteAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to edit this address?.
        /// </summary>
        internal static string AskToEditAddress
        {
            get
            {
                return ResourceManager.GetString("AskToEditAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to edit list of addresses?.
        /// </summary>
        internal static string AskToEditAddresses
        {
            get
            {
                return ResourceManager.GetString("AskToEditAddresses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want view a customer detail?.
        /// </summary>
        internal static string AskToViewCustomerDetail
        {
            get
            {
                return ResourceManager.GetString("AskToViewCustomerDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer was deleted !.
        /// </summary>
        internal static string CustomerWasDeleted
        {
            get
            {
                return ResourceManager.GetString("CustomerWasDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate Email!.
        /// </summary>
        internal static string DuplicateEmail
        {
            get
            {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate Id!.
        /// </summary>
        internal static string DuplicateId
        {
            get
            {
                return ResourceManager.GetString("DuplicateId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email is incorrect!.
        /// </summary>
        internal static string EmailIsInvalid
        {
            get
            {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Id is not empty and length is not greater than 10!.
        /// </summary>
        internal static string IdIsInvalid
        {
            get
            {
                return ResourceManager.GetString("IdIsInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name is not empty and length is not greater than 50!.
        /// </summary>
        internal static string NameIsInvaild
        {
            get
            {
                return ResourceManager.GetString("NameIsInvaild", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone Number is incorrect!.
        /// </summary>
        internal static string PhoneNumberIsInvalid
        {
            get
            {
                return ResourceManager.GetString("PhoneNumberIsInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Place is empty!.
        /// </summary>
        internal static string PlaceIsEmpty
        {
            get
            {
                return ResourceManager.GetString("PlaceIsEmpty", resourceCulture);
            }
        }
    }
}
